### PR TITLE
Add 2017 baseline and rate

### PR DESCRIPTION
**Pull request by colinxfleming**
Hey friends -- we're a project at Code for DC / DCAF Engineering, and we're probably going to be doing some FPL related stuff in the not too distant future. Was looking at the app and curling the API for funsies, and figured I would pay it forward by adding the 2017 rates to the dict.

Please review at your convenience, absolutely no rush. Thanks much for spinning up this project, it's pretty handy.

I pulled the rates from https://www.healthcare.gov/glossary/federal-poverty-level-FPL/ -- here's a screenshot of what they had when I looked:

screen shot 2018-02-25 at 10 40 13 pm

Let me know if you'd like any changes for this.

cc @mdworken @lomky for awareness

### CODE REVIEW

**Comment by mapsam** [comment]
Thank you @colinxfleming! 🙏 Appreciate you keeping this up-to-date

**Comment by mapsam** [comment]
Noting that I updated the default year to 2017 in https://github.com/codeforamerica/fplapi/commit/4a68619df5cf606ce495c4ac4f9d71dd1a3926dd

**Comment by mapsam** [comment]
And this has been deployed! 

http://fplapi.herokuapp.com/api?size=3&income=3000&income_type=monthly shows 2017 numbers

**Comment by colinxfleming** [comment]
thanks a bunch @mapsam ! if I see the 2018 numbers come out I'll bump again.

**Pull request merged**
